#! /bin/sh
code --install-extension christian-kohler.path-intellisense
code --install-extension GitHub.github-vscode-theme
code --install-extension huytd.github-light-monochrome
code --install-extension be5invis.theme-verandi
code --install-extension Gruntfuggly.todo-tree
code --install-extension hediet.vscode-drawio
code --install-extension jamesmaj.easy-icons
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension njpwerner.autodocstring
code --install-extension reverbc.vscode-pytest
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tamasfe.even-better-toml
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
