#!/bin/bash

set -e

root_dir=$(git root-dir)


if [[ $(uname -s) == MINGW* ]]; then
    venv_path=$DOTFILES/.venv/Scripts
else
    venv_path=$DOTFILES/.venv/bin
fi

$venv_path/flake8 --extend-ignore=E203 --max-line-length=88 --exclude=.git,.venv,__pycache__ $root_dir
$venv_path/black --check .
