#!/bin/bash

set -ex

root_dir=$(git root-dir)


if [[ $(uname -s) == MINGW* ]];
then
    python_bin=$DOTFILES/.venv/Scripts/python
else
    python_bin=$DOTFILES/.venv/bin/python
fi

$python_bin ruff $root_dir
$python_bin ruff format --check $root_dir
