#!/bin/bash

set -e

root_dir=$(git root-dir)


if [[ $(uname -s) == MINGW* ]];
then
    python_bin=$root_dir/.venv/Scripts/python
else
    python_bin=$root_dir/.venv/bin/python
fi

$python_bin -m ruff check $root_dir
$python_bin -m ruff format --check $root_dir
