#! /bin/bash

BRANCHES="develop master main"
ROOT=$(git root-dir)

for branch in $BRANCHES
do
    git rev-parse --verify $branch &> /dev/null
    if [ $? -eq 0 ];
    then 
        git stash push ${ROOT} &> /dev/null
        git checkout $branch &> /dev/null
        git stash pop &> /dev/null
        echo "Switched to $branch"
        exit 0
    fi
done
exit 1


