#! /bin/env sh

__build_jupyter_image () {
    __CURENT_DIR=$(pwd)
    cd $DOTFILES
    docker build -f ./docker/jupyter.Dockerfile --build-arg PY_VERSION=$1 -t jupyter:$1 .
    cd $__CURENT_DIR
}

PYVERSION=${1:-"3.10"}
__COUNT_OF_IMAGES=$(docker images | grep "jupyter" | awk "{print $2}" | grep "$PYVERSION" | wc -l)
if [ $__COUNT_OF_IMAGES -eq 0 ];
then
    __build_jupyter_image $PYVERSION
fi
docker run --rm -d -p 8888:8888 jupyter:$PYVERSION
sleep 10
open https://localhost:8888
