#! /usr/bin/env bash

if [ ! -d "./.venv" ];
then
    py -m venv ./.venv
    if [ -d "./.venv/bin/" ];
    then
        ./.venv/bin/python -m pip install --upgrade pip setuptools
    else
        ./.venv/Scripts/python.exe -m pip install --upgrade pip setuptools
    fi
fi
