#! /usr/bin/env bash

if [ "${VIRTUAL_ENV+x}" = "x" ];
then
    command python "$@"
elif [ -d './.venv/Scripts' ];
then
    ./.venv/Scripts/python.exe "$@"
elif [ -d './.venv/bin' ];
then
    ./.venv/bin/python3 "$@"
elif [[ $(uname -s) == MINGW* ]];
then
    winpty -Xallow-non-tty python.exe "$@"
else
    python3 "$@"
fi

