version: "3"

services:
  dev:
    user: py-remote
    image: py-dev:3.8
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  #   environment:
  #     DATABASE_CONNECTION_STRING: postgresql://postgres:postgres@db/postgres
  #     RABBIT_MQ_CONNECTION_STRING: amqp://user:password@rabbit_mq:5672/
  #     AZURITE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure:10000/devstoreaccount1;"

  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres

  # liquibase:
  #   image: liquibase/liquibase:3.10.x
  #   depends_on:
  #     db
  #   restart: on-failure
  #   volumes:
  #     - ../scripts/liquibase:/liquibase/changelog
  #   command: --url="jdbc:postgresql://db:5432/postgres" --changeLogFile=changelog/changelog.xml --username=postgres --password=postgres update

  # redis:
  #   image: redis
  #   restart: unless-stopped

  # rabbit_mq:
  #   image: rabbitmq:3.8-management
  #   restart: always
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password

  # azure_blob:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   command:
  #     [
  #       "azurite",
  #       "-l",
  #       "/data",
  #       "--blobHost",
  #       "0.0.0.0",
  #       "--queueHost",
  #       "0.0.0.0",
  #       "--loose",
  #     ]
