export DOTFILES="${HOME}/.dotfiles"

source $DOTFILES/shell/default_rc
source $DOTFILES/bash/aliases.sh
source $DOTFILES/bash/prompt.sh

if [[ $(uname -s) == MINGW* ]];
then
    export PATH=$PATH:$HOME/.bin/bin
    export TMP=$HOME/.tmp
    export TEMP=$HOME/.tmp
    export NVIM_LISTENING_ADRESS=$HOME/.tmp/nvim_0
fi
